loss:
  w_mse: 1.
  kurtosis: 1.8
  w_kurtosis: 1E-5
  w_skew: 0.0
  w_kl_divergence: 0.0
  w_z_l1_reg: 0.0

data:
  dataset: imagenet2012
  train_split: train
  val_split: validation
  image_size:
    - 224
    - 224
    - 3
  
training:
  beta: 0.98
  learning_rate: 1E-4
  batch_size: 512
  max_epochs: 10

model:
  latent_dimensions: 2000
  layers:
    - 32
    - 64
  decoder_dense_filters: 32
